## [B]Nutritional content of different food

We first paste in our fdc api key and install our dependencies via requirements.txt:

In [63]:
apikey = "6k4anDq3cih8Tre4oqT28vAxd5dKKOAfKm53hdWx"

In [64]:
%pip install -r ../requirements.txt --upgrade -q
!pip install fooddatacentral
!pip install pint

ERROR: Could not open requirements file: [Errno 2] No such file or directory: '../requirements.txt'
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: fooddatacentral in /srv/conda/lib/python3.11/site-packages (1.0.12)
Requirement already satisfied: pint in /srv/conda/lib/python3.11/site-packages (0.25.3)
Requirement already satisfied: flexcache>=0.3 in /srv/conda/lib/python3.11/site-packages (from pint) (0.3)
Requirement already satisfied: flexparser>=0.4 in /srv/conda/lib/python3.11/site-packages (from pint) (0.4)
Requirement already satisfied: platformdirs>=2.1.0 in /srv/conda/lib/python3.11/site-packages (from pint) (4.3.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /srv/conda/lib/python3.11/site-packages (from pint) (4.12.2)

Import the necessary packages for pulling and processing data:

In [65]:
import pandas as pd
import fooddatacentral as fdc

In [66]:
from  scipy.optimize import linprog as lp
import numpy as np
import warnings

import pandas as pd
import numpy as np
import warnings
from scipy.optimize import linprog as lp

import pandas as pd
import numpy as np
import warnings
from scipy.optimize import linprog as lp

def solve_subsistence_problem(FoodNutrients, Prices, dietmin, max_weight=None, tol=1e-6, drop_vitamins=None):
    """
    Solves Stigler's Subsistence Cost Problem using minimum requirements.
    """
    
    vitamin_map = {
        'A': 'Vitamin A, RAE',
        'E': 'Vitamin E (alpha-tocopherol)',
        'C': 'Vitamin C, total ascorbic acid'
    }

    if drop_vitamins is not None:
        if isinstance(drop_vitamins, str):
            drop_vitamins = [drop_vitamins]
            
        labels_to_drop = [vitamin_map[v.upper()] for v in drop_vitamins if v.upper() in vitamin_map]
        
        dietmin = dietmin.drop(labels=labels_to_drop, errors='ignore')

    
    try: 
        p = Prices.apply(lambda x: x.magnitude)
    except AttributeError: 
        p = Prices

    p = p.dropna()
    use = p.index.intersection(FoodNutrients.columns)
    p = p[use]

    A = FoodNutrients[p.index].fillna(0)
    A = A.loc[A.index.intersection(dietmin.index)]
    A = A.reindex(dietmin.index, axis=0)
    b = dietmin

    A = A.reindex(p.index, axis=1)
    A = A.reindex(b.index, axis=0)

    result = lp(p.values, -A.values, -b.values, method='highs')

    result.A = A
    result.b = b
    
    if result.success:
        result.diet = pd.Series(result.x, index=p.index)
    else:
        warnings.warn(result.message)
        result.diet = pd.Series(np.nan, index=p.index)

    return result

In [67]:
dfNG = pd.DataFrame({
    "Food": [
        "Malt drinks",
        "Soft drinks (Coca Cola, spirit, etc)",
        "Plantains",
        "Yam--roots",
        "Milk powder",
        "Chicken",
        "Condiments",
        "Tea",
        "Sachet water",
        "Palm oil",
        "Chocolate drinks",
        "Milk tinned (unsweetened)",
        "Tomato puree (canned)",
        "Fish--frozen",
        "Eggs",
        "Orange/tangerine",
        "Bread",
        "Groundnut oil",
        "Beef",
        "Goat",
        "Fish--dried",
        "Maize flour",
        "Rice--local",
        "Sweet potatoes",
        "Fish--smoked",
        "Millet",
        "Gari",
        "Sugar",
        "Maize",
        "Onions",
        "Groundnuts",
        "Fish--fresh",
        "Cassava (root)",
        "White beans",
        "Pepper",
        "Bananas",
        "Guinea corn/sorghum",
        "Cassava flour",
        "Garden eggs/egg plant",
        "Tomatoes",
        "Other vegetables (fresh or canned)",
        "Rice--imported",
        "Brown beans",
        "Okra",
        "Leaves (Cocoyam, Spinach, etc.)"
    ]
})

In [68]:
def get_fdc_id(food_name):
    try:
        results = fdc.search(apikey, food_name)

        if results is not None and len(results) > 0:
            return results.iloc[0]["fdcId"]   # not results[0]["fdcId"]
        else:
            return None

    except Exception as e:
        print(f"Error for {food_name}: {e}")
        return None

In [69]:
dfNG["FDC"] = dfNG["Food"].apply(get_fdc_id)
dfNG["FDC"] = dfNG["FDC"].astype("Int64")
dfNG.head()

                                   Food      FDC
0                           Malt drinks   174866
1  Soft drinks (Coca Cola, spirit, etc)  2710541
2                             Plantains  2709563
3                            Yam--roots   170071
4                           Milk powder  2673399

In [70]:
nutrient_df = fdc.nutrients(apikey, "2673399")
nutrient_df

                              Quantity Units
Sodium, Na                      417.00    mg
Fatty acids, total saturated      0.00     g
Energy                          375.00  kcal
Potassium, K                   1708.00    mg
Total lipid (fat)                 0.00     g
Fatty acids, total trans          0.00     g
Iron, Fe                          0.00    mg
Calcium, Ca                    1292.00    mg
Cholesterol                       0.00    mg
Sugars, added                     0.00     g
Total Sugars                     45.83     g
Vitamin D (D2 + D3)               0.00    µg
Fiber, total dietary              4.20     g
Carbohydrate, by difference      54.17     g
Protein                          33.33     g

In [71]:
dfNG["FDC"] = dfNG["FDC"].astype("Int64")
dfNG.head()

                                   Food      FDC
0                           Malt drinks   174866
1  Soft drinks (Coca Cola, spirit, etc)  2710541
2                             Plantains  2709563
3                            Yam--roots   170071
4                           Milk powder  2673399

In [72]:
food_nutrient_dict = {}
failed_foods = []

for _, row in dfNG.iterrows():
    food = row["Food"]
    fdc_code = row["FDC"]

    try:
        if pd.notna(fdc_code):
            # IMPORTANT FIX: string + no decimals
            nutrient_df = fdc.nutrients(apikey, str(int(fdc_code)))

            if nutrient_df is not None and "Quantity" in nutrient_df.columns:
                food_nutrient_dict[food] = nutrient_df["Quantity"]
            else:
                failed_foods.append(food)
        else:
            failed_foods.append(food)

    except Exception as e:
        print(f"{food} failed: {e}")
        failed_foods.append(food)

In [73]:
FoodNutrientsNG = pd.DataFrame(food_nutrient_dict)
FoodNutrientsNG_T = FoodNutrientsNG.T

FoodNutrientsNG_T.head()

,Alanine,"Alcohol, ethyl",Amino acids,Arginine,Ash,Aspartic acid,Betaine,Caffeine,"Calcium, Ca","Carbohydrate, by difference",...,Vitamin D2 (ergocalciferol),Vitamin D3 (cholecalciferol),Vitamin E (alpha-tocopherol),"Vitamin E, added",Vitamin K (Dihydrophylloquinone),Vitamin K (Menaquinone-4),Vitamin K (phylloquinone),Vitamins and Other Components,Water,"Zinc, Zn"
Malt drinks,NaN,0.0,0.0,NaN,1.90,NaN,NaN,37.0,60.0,86.94,...,NaN,NaN,0.17,0.0,NaN,NaN,2.5,0.0,1.30,0.80
"Soft drinks (Coca Cola, spirit, etc)",NaN,0.0,NaN,NaN,NaN,NaN,NaN,9.0,1.0,10.40,...,NaN,NaN,0.00,0.0,NaN,NaN,0.0,NaN,89.40,0.09
Plantains,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,9.0,63.80,...,NaN,NaN,5.04,0.0,NaN,NaN,28.6,NaN,2.09,0.37
Yam--roots,0.063,0.0,0.0,0.127,0.82,0.155,NaN,0.0,17.0,27.88,...,NaN,NaN,0.35,0.0,NaN,NaN,2.3,0.0,69.60,0.24
Milk powder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1292.0,54.17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
FoodNutrientsNG_T.to_csv("FoodNutrientsNG.csv")

In [75]:
wanted_nutrients = [
    "Energy",
    "Protein",
    "Total lipid (fat)",
    "Carbohydrate, by difference",
    "Fiber, total dietary",
    "Calcium, Ca",
    "Iron, Fe",
    "Potassium, K",
    "Sodium, Na"
]

clean_sheet = FoodNutrientsNG_T[wanted_nutrients]
clean_sheet

,Energy,Protein,Total lipid (fat),"Carbohydrate, by difference","Fiber, total dietary","Calcium, Ca","Iron, Fe","Potassium, K","Sodium, Na"
Malt drinks,1720.0,5.100000,4.760,86.940000,4.800,60.00,2.280,618.0,190.00
"Soft drinks (Coca Cola, spirit, etc)",42.0,0.000000,0.250,10.400000,0.000,1.00,0.020,5.0,3.00
Plantains,531.0,2.280000,29.600,63.800000,3.500,9.00,0.970,786.0,202.00
Yam--roots,494.0,1.530000,0.170,27.880000,4.100,17.00,0.540,816.0,9.00
Milk powder,375.0,33.330000,0.000,54.170000,4.200,1292.00,0.000,1708.0,417.00
Chicken,188.0,24.710000,9.410,1.180000,0.000,0.00,0.420,NaN,353.00
Condiments,1136.0,16.960000,16.220,14.430000,1.000,106.00,2.180,242.0,480.00
Tea,34.0,0.000000,0.000,8.460000,NaN,NaN,NaN,NaN,2.00
Sachet water,0.0,0.000000,0.000,0.000000,0.000,3.00,0.000,0.0,4.00
Palm oil,3699.0,0.000000,100.000,0.000000,0.000,0.00,0.010,0.0,0.00
Chocolate drinks,49.0,0.640000,0.400,10.700000,0.600,100.00,0.330,79.0,91.00
Milk tinned (unsweetened),15.0,0.550000,1.220,0.340000,0.000,173.00,0.290,31.0,60.00
Tomato puree (canned),NaN,1.578125,0.265,8.036875,1.971,17.64,1.237,416.4,29.36
Fish--frozen,1160.0,11.010000,16.230,21.660000,1.500,16.00,0.840,185.0,402.00
Eggs,136.0,13.640000,9.090,0.000000,NaN,45.00,1.640,NaN,136.00
Bread,240.0,8.000000,1.000,50.000000,2.000,0.00,3.600,NaN,560.00
Groundnut oil,102.0,12.010000,4.240,4.240000,0.700,9.00,0.710,66.0,201.00
Beef,129.0,20.000000,5.880,0.000000,0.000,0.00,4.240,NaN,212.00
Goat,142.0,26.900000,3.010,0.000000,0.000,17.00,3.700,402.0,392.00
Fish--dried,1212.0,62.820000,2.370,0.000000,0.000,160.00,2.500,1458.0,7027.00
Maize flour,1524.0,8.750000,5.090,73.890000,8.400,5.00,1.740,381.0,5.00
Rice--local,112.0,5.120000,2.250,17.200000,0.600,15.00,1.770,85.0,316.00
Sweet potatoes,85.0,1.690000,0.000,20.340000,3.400,30.00,0.850,337.0,55.00
Fish--smoked,116.0,25.200000,0.960,0.000000,0.000,49.00,1.400,415.0,763.00
Millet,118.0,3.500000,1.000,23.600000,1.300,3.00,0.630,62.0,168.00
Gari,339.0,1.790000,1.790,78.570000,0.000,0.00,0.000,NaN,41.00
Sugar,375.0,0.000000,0.000,100.000000,NaN,NaN,NaN,NaN,0.00
Onions,38.0,0.860000,0.080,8.460000,1.700,17.00,0.240,171.0,1.00
Groundnuts,102.0,12.010000,4.240,4.240000,0.700,9.00,0.710,66.0,201.00
Fish--fresh,602.0,23.330000,4.900,0.000000,0.000,8.00,1.020,252.0,39.00
Cassava (root),191.0,1.420000,3.030,39.600000,1.900,17.00,0.280,282.0,145.00
White beans,85.0,6.150000,0.000,14.620000,4.600,62.00,2.080,NaN,292.00
Pepper,333.0,0.000000,0.000,66.670000,33.300,437.00,28.900,NaN,0.00
Bananas,1448.0,3.890000,1.810,88.280000,9.900,22.00,1.150,1491.0,3.00
Cassava flour,371.0,0.000000,0.000,88.570000,5.700,57.00,0.000,303.0,0.00
Tomatoes,14.0,0.000000,0.000,2.820000,NaN,NaN,NaN,NaN,0.00
Other vegetables (fresh or canned),39.0,3.240000,0.390,5.740000,2.100,8.00,0.280,420.0,7.00
Rice--imported,537.0,22.160000,4.360,0.100000,0.000,4.00,2.270,338.0,40.00
Brown beans,162.0,6.400000,4.540,24.300000,3.900,53.00,2.230,345.0,213.00
Okra,44.0,3.000000,0.000,8.000000,1.000,80.00,0.540,NaN,3.00
"Leaves (Cocoyam, Spinach, etc.)",268.0,9.400000,1.400,8.280000,2.000,185.00,4.000,337.0,9.00